version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - gocritic
    - errorlint
    - asciicheck
    - bidichk
    - copyloopvar
    - durationcheck
    - dupword
    - exhaustive
    - prealloc
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: indent-error-flow
